# Generated by Django 6.0.2 on 2026-02-09 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='time_slot',
            field=models.CharField(choices=[('LUNCH', 'Lunch Break (12:00 PM - 2:00 PM)'), ('EVENING', 'Evening Outing (4:00 PM - 7:00 PM)'), ('WEEKEND', 'Weekend Pass (8:00 AM - 8:00 PM)'), ('EMERGENCY', 'Emergency / Medical (Anytime)')], default='EVENING', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
