# Generated by Django 6.0.2 on 2026-02-09 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_timeslot'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                (lambda TimeSlot, VisitRequest: (
                    [
                        (lambda choice_label, label, start, end: (
                            TimeSlot.objects.create(label=label, start_time=start, end_time=end)
                        ))('LUNCH', 'Lunch Break', '12:00', '14:00'),
                        (lambda choice_label, label, start, end: (
                            TimeSlot.objects.create(label=label, start_time=start, end_time=end)
                        ))('EVENING', 'Evening Outing', '16:00', '19:00'),
                        (lambda choice_label, label, start, end: (
                            TimeSlot.objects.create(label=label, start_time=start, end_time=end)
                        ))('WEEKEND', 'Weekend Pass', '08:00', '20:00'),
                        (lambda choice_label, label, start, end: (
                            TimeSlot.objects.create(label=label, start_time=start, end_time=end)
                        ))('EMERGENCY', 'Emergency / Medical', '00:00', '23:59')
                    ],
                    # After creating, map old VisitRequest.time_slot values to the created TimeSlot IDs
                    (lambda : (
                        [
                            VisitRequest.objects.filter(time_slot='LUNCH').update(time_slot=str(TimeSlot.objects.filter(label__icontains='Lunch').first().pk)),
                            VisitRequest.objects.filter(time_slot='EVENING').update(time_slot=str(TimeSlot.objects.filter(label__icontains='Evening').first().pk)),
                            VisitRequest.objects.filter(time_slot='WEEKEND').update(time_slot=str(TimeSlot.objects.filter(label__icontains='Weekend').first().pk)),
                            VisitRequest.objects.filter(time_slot='EMERGENCY').update(time_slot=str(TimeSlot.objects.filter(label__icontains='Emergency').first().pk)),
                        ]
                    ))()
                ))(apps.get_model('visitors', 'TimeSlot'), apps.get_model('visitors', 'VisitRequest'))
            ),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitors.timeslot'),
        ),
    ]
